apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: mysql
  annotations:
    description: "This pod is created to demonistrate pod annotations"
    jenkins: "https://jenkins.com/devops/build/job/roboshop-catalouge/3"
spac:
  containers:
  - name: nginx
    image: nginx